org: 03difoha
app: ase
service: ase

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

package:
  excludeDevDependencies: true
  exclude:
     - ase-api/__pycache__
     - ase-api/.serverless
     - ase-api/.serverless/ase.zip
     - ase-api/venv
     - ase-api/node_modules
     - ase-api/ukpostcodes.csv

